### ISSUE TITLE
Load works badly

### ISSUE THREAD

**Issue by eric-burel** [naoxink/devlife#10]
Hi,
There are few issues when saving and loading the game (using Chromium) :
- I can't fire people anymore
- When having a project manager, I can't research autostart project anymore 
(the game behaves as if I had no employee)
- Computer price start from the lowest, eventhough the computer version is correct
- Research time restart from zero

This is an incredibly addictive game, hope it will get better and better !

**Comment by tarellel** [comment]
To add on to what @eric-burel stated, while loading from (Chrome)

* Not only can you not fire, but you can't hire anymore either (buttons are disabled)
* Tech improvements also seem to be reset to zero.
* Project, Improvements, and buff/shop times are zeros out instead of maintaining their previous state.

**Comment by naoxink** [comment]
I think all those problems are fixed in this commit: https://github.com/naoxink/devlife/commit/e2d84352977802c03d4528b14903beec4e1aa5ba

Thank you 👍
